FROM python:3.12-slim
WORKDIR /app
COPY requirements-mlflow.txt .
RUN pip install --no-cache-dir -r requirements-mlflow.txt
COPY docker/mlflow_entrypoint.sh ./mlflow_entrypoint.sh
RUN chmod +x ./mlflow_entrypoint.sh
EXPOSE 5000
ENTRYPOINT ["./mlflow_entrypoint.sh"]
